// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZXWi7uaP3al4g5T4YWJRHPRVEAecBTNY',
    appId: '1:286552199323:web:b365fdcc846534ade8b63e',
    messagingSenderId: '286552199323',
    projectId: 'seyaqti-mobile-app',
    authDomain: 'seyaqti-mobile-app.firebaseapp.com',
    storageBucket: 'seyaqti-mobile-app.appspot.com',
    measurementId: 'G-66BYXPDE2M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA61cbvaOWWxxpT214NtyGB_qWzt-BXV_k',
    appId: '1:286552199323:android:6e1cd92c0d6db879e8b63e',
    messagingSenderId: '286552199323',
    projectId: 'seyaqti-mobile-app',
    storageBucket: 'seyaqti-mobile-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA2UGqJYlJBDUZwJlgho_zxg7Lst1W75c',
    appId: '1:286552199323:ios:58d9f550c8b4523ae8b63e',
    messagingSenderId: '286552199323',
    projectId: 'seyaqti-mobile-app',
    storageBucket: 'seyaqti-mobile-app.appspot.com',
    iosClientId: '286552199323-73hv7bdu44en8jvltlbvjrcsc7dklscq.apps.googleusercontent.com',
    iosBundleId: 'com.example.seyaqtiApp',
  );
}
